### ISSUE TITLE
Opinion: FilmCore has role attributes

### ISSUE THREAD

**Issue by taiyop** [Spiral-AI/SpiralFilm#11]
In my use case, I want to write the beginning of a sentence and have chaGPT write the continuation sentence.

e.g.
<img width="1200" alt="image" src="https://github.com/Spiral-AI/SpiralFilm/assets/1048048/52239fc0-926e-4b7f-bb6c-120d8187453f">

### Just idea of  how to use.

```
f = FilmCore(
    role="assistant"
    prompt="""
Once upon a time there was an old man and an old woman. they have one child but
"""
    system_prompt="""
your role is professional novel writer.

Please write the beginning of a sentence and have chatgpt write the continuation sentencein a modern way.
"""
).run()
```

----原文---
UseCaseとして role: assistantとして文の始まりを与え、chatGPTにはその続きを書かせてみたい場合を想定しています。

**Comment by ysasaki6023** [comment]
Thank you for proposing this use-case.
In this case you can write as follow.

```
f = FilmCore(prompt="""
Once upon a time there was an old man and an old woman. they have one child but 
""",
    system_prompt="""
your role is professional novel writer.

Please write the beginning of a sentence and have chatgpt write the continuation sentencein a modern way.
"""
).run()
```

This code will output the expected sentences shown in your example.

We intentionally omitted "role" parameter because it is complicated for the users. We try hiding these chat specific features to keep SpiralFilm a tool to focus on "question" and "answer" machine.

**Comment by ysasaki6023** [comment]
One more point before closing. As far as we observed, this way of asking doesn't harm the performance and gives expected continuing sentences.
Not sure how GPT-3.5-turbo and GPT-4 are trained, but probably they're trained such that they have the same capability as previous davinci completion to keep some compatibility.
